# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vd_oxt9tj8lFO2TGZI2ModANqtNPVWrw
"""

!pip install selenium
!apt-get update
!apt-get install -y chromium-browser
!apt-get install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install yfinance

import yfinance as yf
import pandas as pd

# Download Tesla stock data from 2010 to the current date
tesla_data = yf.download("TSLA", start="2010-06-29", end="2023-12-31")

# Reset index to make 'Date' a column instead of an index
tesla_data.reset_index(inplace=True)

# Ensure the 'Date' column is in datetime format (if not already)
tesla_data['Date'] = pd.to_datetime(tesla_data['Date'])

# Sort the data by date
tesla_data = tesla_data.sort_values('Date')

# Check the first few rows of data
tesla_data.head()

import yfinance as yf
import matplotlib.pyplot as plt

# Fetch GameStop stock data from Yahoo Finance
gme_data = yf.download('GME', start='2020-01-01', end='2024-01-01')

# Check if the data is fetched correctly
print(gme_data.tail())  # Display the last 5 rows to verify

# Define the make_graph function
def make_graph(data, x_column, y_column, title):
    plt.figure(figsize=(10, 6))
    plt.plot(data.index, data[y_column], label='Stock Price')
    plt.title(title)
    plt.xlabel(x_column)
    plt.ylabel(y_column)
    plt.legend()
    plt.grid(True)
    plt.show()

# Call the make_graph function for GameStop stock
make_graph(gme_data, 'Date', 'Close', 'GameStop Stock Price Over Time')

import yfinance as yf
import pandas as pd

# Download Tesla stock data
tesla_data = yf.download("TSLA", start="2010-06-29", end="2023-12-31")
tesla_data.reset_index(inplace=True)  # Reset index to get Date as a column

# Ensure the Date column is of datetime type
tesla_data['Date'] = pd.to_datetime(tesla_data['Date'])

# Sort the data by Date (optional but ensures consistency)
tesla_data = tesla_data.sort_values('Date')